### ISSUE TITLE
Feature Request: Fullscreen support

### ISSUE THREAD

**Issue by pateldhruv1993** [panzi/embedplayer#5]
I couldn't find any way to make the player fullscreen using your library or detect if the player is fullscreen. I think having that would be really nice. Also changing source of the video without having to escape out of fullscreen would be nice too for having playlists.

**Comment by panzi** [comment]
Yeah, fullscreen would be a possible future feature, but my spare time is currently occupied with other stuff. Keeping fullscreen on video change would be a problem, because that's not supported by all video providers (I had the case where the old video keeps being fullscreen and the other starts to play in the background) and it definitely does not work cross video provider.

What would work is making an enclosing `<div>` fullscreen and the video element fill that `<div>`. Then whatever is playing is fullscreen, but things like YouTube videos might still have their own fullscreen button which makes everything confusing. And sometimes players have different controls when in fullscreen, which would no be the case doing it like that. And I don't know how this all would work out on phones.

**Comment by pateldhruv1993** [comment]
The feature would probably not work at all on mobile as even youtube cannot handle video change gracefully on their mobile playlists. But feels definitely worth implementing just for desktop. Also as long as we can listen to send fullscreen events I believe your solution of using div wrapper might work just fine (not considering the edge case of different player UI on fullscreen).

**Comment by panzi** [comment]
I added this text about fullscreen support to the README:

Embed player doesn't provide an API for toggling a video to fullscreen because player
APIs don't provide a method for that. You can use the HTML5 fullscreen API to implement
this feature yourself, though:

```HTML
<button onclick="$('#embed')[0].requestFullscreen();">Fullscreen</button>
```

**NOTE:** The players *do* provide their own fullscreen buttons. Just adding your own
will get you a situation where you can enter fullscreen twice and get situations that
are very confusing to users. If you don't set the `allowfullscreen` attribute on the
iframe some players will still render a grayed out non-functional fullscreen button,
which is still confusing. So maybe just let this be handeled by the players.

https://github.com/panzi/embedplayer#fullscreen-support
